### ISSUE TITLE
Feature request: support SageMaker SDK v2

### ISSUE THREAD

**Issue by juliensimon** [Kenza-AI/sagify#121]
Hi,

Sagemaker SDK v2 is coming very soon. It has a number of breaking changes that will impact Sagify. Nothing huge, but you may want to adapt the code.

https://github.com/aws/sagemaker-python-sdk/issues/1459
https://sagemaker.readthedocs.io/en/v2.0.0.rc1/v2.html

**Comment by pm3310** [comment]
Hi @juliensimon ,

Thank you for your message :-) This is very high in our backlog :-)

**Comment by pm3310** [comment]
@juliensimon Fixed in version 0.20.8 :-) https://github.com/Kenza-AI/sagify/pull/127
