### ISSUE TITLE
motivation is missing

### ISSUE THREAD

**Issue by hanan-vian** [Kenza-AI/sagify#122]
please add to the README.md the motivation for this package. 
Why should one use this? What limitation of SageMaker is it trying to solve?
What can it do that SageMaker cannot?

**Comment by pm3310** [comment]
Hi @hanan-vian thank you for your comment :-) Sagify is a layer on top of Sagemaker so that to hide all low level details of Sagemaker. You just need to implement 2 functions, a train function with your training logic, and a predict function for inference when you deploy your model.
