### ISSUE TITLE
Installing the latest version downloads all versions of `boto3` and `botocore` until it fails

### ISSUE THREAD

**Issue by dgallitelli** [Kenza-AI/sagify#135]
On all the devices I've tested - SageMaker Notebooks, SageMaker Notebook Instance (AL1 and AL2), personal MacBook 11.6 - I haven't been able to download and install `sagify` (neither current or older version. This is caused by some dependencies that fail to cohexist. In particular, it tries to download and install every `boto3` and `botocore` package in existance, until eventually finding that:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anaconda-project 0.9.1 requires ruamel-yaml, which is not installed.
docker-compose 1.29.2 requires docker[ssh]>=5, but you have docker 3.7.3 which is incompatible.
black 20.8b1 requires click>=7.1.2, but you have click 7.0 which is incompatible.
awscli 1.21.3 requires botocore==1.22.3, but you have botocore 1.18.18 which is incompatible.
awscli 1.21.3 requires s3transfer<0.6.0,>=0.5.0, but you have s3transfer 0.3.7 which is incompatible.
anyio 2.1.0 requires idna>=2.8, but you have idna 2.7 which is incompatible.
aiobotocore 1.3.0 requires botocore<1.20.50,>=1.20.49, but you have botocore 1.18.18 which is incompatible.
```

I can provide multiple tracelogs here: 

SageMaker Notebook Instance AL2:
[tracelog-sagemaker-notebook-instance-al2.txt](https://github.com/Kenza-AI/sagify/files/7498985/tracelog-sagemaker-notebook-instance-al2.txt)

SageMaker Notebooks (SM Studio):
[tracelog-sagemaker-notebooks-studio.txt](https://github.com/Kenza-AI/sagify/files/7498986/tracelog-sagemaker-notebooks-studio.txt)

Macbook Pro:
[tracelog-macbook-pro.txt](https://github.com/Kenza-AI/sagify/files/7499192/tracelog-macbook-pro.txt)

**Comment by pm3310** [comment]
Thank you for catching this @dgallitelli @jornfranke . I'm looking into this

**Comment by pm3310** [comment]
Hey @dgallitelli and @jornfranke , there's a new version of Sagify deployed, 0.21.1. It should solved this issue. Pls, let me know if you still experience the same problem
