### ISSUE TITLE
Library stopped being maintained?

### ISSUE THREAD

**Issue by gabriel-fsa** [Kenza-AI/sagify#146]
I was curious to know, because this library saved me a lot. I spent the whole weekend looking for ways to integrate a spacy model and had given up hope.

**Comment by pm3310** [comment]
Hi @gabriel-fsa , glad to hear. I'm still maintaining it.

**Comment by pm3310** [comment]
@gabriel-fsa Can I ask how exactly you used Sagify for your project?

**Comment by gabriel-fsa** [comment]
@pm3310 I will use it to deploy a spacy model (en_core_web_trf) in sagemaker, there is no aws SDK for spacy. And looking on the internet I didn't find any article exemplifying the requirements to have in docker, and sagify already has this in sagify_base.

**Comment by pm3310** [comment]
Gotcha, thanks @gabriel-fsa
