### ISSUE TITLE
Make Docker tags configurable

### ISSUE THREAD

**Issue by berlinquin** [Kenza-AI/sagify#33]
I would find it helpful to be able to specify a tag for the Docker image being used. This would allow a user to maintain a Docker build history, and to easily switch between different models.

For example, I would like to be able to run the command `sagify --tag test build -d src` to build an image but tag it as 'test' instead of 'latest', the default tag.

Since all of the commands access the Docker image under the hood, I think this needs to be a global option available to all subcommands, similar to the --verbose flag.

I see two ways to approach this:

1. Use the click library's built-in [context](http://click.pocoo.org/5/commands/#nested-handling-and-contexts) object. This would make it easy to pass the option to subcommands, but it would require changing the method signature for each subcommand.

2. Create a service class and store the current tag as a global var. This global could be imported where needed. This approach does not change any method signatures but requires an extra import.

I would prefer to go with option 1, since it would allow more global arguments to be added more easily in the future. It would also keep the structure cleaner by not requiring an extra class to be created and maintained.

@pm3310 lmk which seems more consistent with the project, and I can build it.

**Comment by pm3310** [comment]
I really like the idea of having tags on Docker images and maintaining a history. It will be very useful.

I prefer option 1. Even though the signature of subcommands will change, it's an incremental change as `tag` could be optional.

The default behaviour could remain the same.

Keep in mind that there is already in `cloud train` and `cloud deploy` the optional arg `tags` for passing aws tags for SageMaker Training Jobs and Endpoint Configurations.

I can think of 3 options:
1. Rename `tags` to smth like `aws_tags` but that means that the signatures will change
2. Name the new arg `docker_tag`, then there will be an incremental change which looks more appealing than option (1).
3. Keep `tag` and `tags` as 2 different args but they're going to be very similar, and end user may be confused.

What are your thoughts on this @berlinquin ?

**Comment by berlinquin** [comment]
Ok, I didn't realize --tags was already an option for cloud train/deploy. I agree that it would be confusing to have both --tag and --tags as arguments.

Which do you see as being a more common use case? I do more local work, so I would use --tag more frequently and would prefer to just rename the current --tags arg to --aws-tags.

However, looking at Click's documentation, these args would never overlap. One would be available as a property on the context parameter, and the other as a separate  parameter.

So, because they don't overlap, I think we could provide multiple aliases for each arg.

i.e. Docker tags can be specified by either --tag or by --docker-tag, and AWS tags can be specified by either --tags or --aws-tags. This allows more a user to be more verbose when neccessary, but have the shorter options as a convenience.

@pm3310 Thoughts?

**Comment by pm3310** [comment]
@berlinquin Sweet! I like your suggestion! Let's do it this way by having multiple aliases for Docker and AWS tags.

The AWS tags are important in big organisations. I work at HomeAway and we specify AWS tags in order to keep track/monitor AWS resources and costs.

**Comment by berlinquin** [comment]
#38
