### ISSUE TITLE
Usage of Sagify in MLflow

### ISSUE THREAD

**Issue by pm3310** [Kenza-AI/sagify#34]
I started using MLflow the other day and it looks very promising. I was happy with MLflow API in general but I couldn't find a way to make a model (trained by mlflow commands) to be deployed on SageMaker.

Additionally, mlflow supports only local training. I think that we could enhance mlflow by enabling training and deployment on SageMaker via Sagify.

What do you think about this @berlinquin ?

**Comment by berlinquin** [comment]
I haven't used mlflow before, but it looks like a nice tool. I saw they had some docs on how to use it with sagemaker, [here](https://mlflow.org/docs/0.2.0/python_api/mlflow.sagemaker.html) and [here](https://mlflow.org/docs/latest/cli.html).

I'd check and see if that does what you need first. It looks like a fairly complex project, so writing a nice integration would be a difficult task.
