### ISSUE TITLE
Local deployment - Errors are not displayed to User

### ISSUE THREAD

**Issue by wfranceys** [Kenza-AI/sagify#36]
Issue: No output is returned to user in case of an error in the python application when local deploying sagify.

- Steps to reproduce: Following the `Getting started guide` then when adding code to the `predict()` function add a syntax error, i.e. in consistent indentation. Then continue following the guide. Then deploy it locally `sagify local deploy -d src`.
- What I expected to see: An indication that something failed due to the error that was added.
- What I saw instead:
```
     ____              _  __
    / ___|  __ _  __ _(_)/ _|_   _
    \___ \ / _` |/ _` | | |_| | | |
     ___) | (_| | (_| | |  _| |_| |
    |____/ \__,_|\__, |_|_|  \__, |
                 |___/       |___/

Started local deployment at localhost:8080 ...
```

----

For others, from @pm3310, in order to debug the error:

Try this:
1. Comment out the last line in `Dockerfile` under `src/sagify/` module. It should look like this `#ENTRYPOINT ["sagify/executor.sh"]`
2. Run `sagify build -d src -r requirements.txt`
3. Run `docker run -it deep-learning-addition-img /bin/bash`. You’ll enter the docker image with this command.
4. As you’re inside the docker img, run `sagify/executor.sh` this should give you your error.

**Comment by berlinquin** [comment]
@wfranceys Try running `sagify --verbose local deploy -d src`. The --verbose flag should log any output, including error messages. lmk if this works.

Also, for debugging a docker image, it's much more convenient to run something like `docker run -it --rm --entrypoint bash deep-learning-addition-img`. @pm3310 Maybe the docs should be updated? The --entrypoint flag for docker run lets you override the entrypoint specified in the Dockerfile.

**Comment by wfranceys** [comment]
@berlinquin Cheers, that does the job, as you said it may help to have the guide as the default :)

**Comment by pm3310** [comment]
@berlinquin @wfranceys I created an issue to update the docs with the `--verbose` arg: https://github.com/Kenza-AI/sagify/issues/37
