### ISSUE TITLE
Pass ECR repository name  

### ISSUE THREAD

**Issue by GuyKerenThe3rd** [Kenza-AI/sagify#39]
Instead of creating a repository per image.

**Comment by ilazakis** [comment]
Closing, we're not actually creating an _ECR_ repository per image, maybe we did so at the time? To control how many ECR repositories you have you can use `configure` to change the image—and consequently the repo—name ala:

`sagify configure --dir dir --image-name repo_name`

If one does not change the image name, no new ECR repos will be created. To add "different images" to the same repo one can simply append a docker tag when pushing. For example,

`sagify configure --dir dir --image-name repo_name`

followed by

`sagify --docker-tag my_tag push -d sagify_dir`

and 

`sagify --docker-tag my_other_tag push -d sagify_dir`

will produce two separate images under the same ECR repo.
