### ISSUE TITLE
Wrong default SageMake failure output folder?

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#45]
Looks like the default value for the failure output directory 'model' passed to [train]( https://github.com/Kenza-AI/sagify/blob/b2f763e1a1d44bc2eb15cc742d4032bca78116df/sagify/template/%7B%7B%20cookiecutter.module_slug%20%7D%7D/training/train#L46) should be 'failure' instead? Based on the [SageMaker docs.](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo.html)
That is, the following:
> default=os.path.join(_DEFAULT_PREFIX_PATH, 'model'),

should be:

> default=os.path.join(_DEFAULT_PREFIX_PATH, 'failure'),

**Comment by pm3310** [comment]
Good catch @ilazakis  I'll fix it
