### ISSUE TITLE
Update to latest SageMaker

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#54]
The latest _SageMaker_ release as of this writing is [1.14.2](https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.14.2).

_Sagify_ is currently [targeting ~1.5](https://github.com/Kenza-AI/sagify/blob/e5555507e3dbd02abe8643b65a691ea31f1c7edd/setup.py#L43)

It's probably good to bring it up to date.

**Comment by pm3310** [comment]
Addressed in https://github.com/Kenza-AI/sagify/issues/60
