### ISSUE TITLE
Validation error in train Command

### ISSUE THREAD

**Issue by royvasu** [Kenza-AI/sagify#57]
Hi,

Receiving this error on running the sagify cloud train command - 

 botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation error detected: failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*

I am following the rest of the steps in the exact same way as mentioned.
Please refer the attachment for my training code
[tran_originalf.txt](https://github.com/Kenza-AI/sagify/files/2614703/tran_originalf.txt)

Regards,
Vasu Roy

**Comment by pm3310** [comment]
Hi @royvasu , 

What name did you give to your sagify app? Did it contain underscores (_). SageMaker doesn't allow TrainingJobs to have underscores in their names. The sagify app that you specify is used as part of the TrainingJob.

Regards,
Pavlos

**Comment by royvasu** [comment]
Thanks a lot.. got it rectified.. probably left a _ with the app name.
