### ISSUE TITLE
Dockerfile Issue

### ISSUE THREAD

**Issue by royvasu** [Kenza-AI/sagify#58]
Hi,
Facing a problem building the image-

The command '/bin/sh -c pip install -r ../sagify-requirements.txt && rm -rf /root/.cache' returned a non-zero code: 1

And
Command '[u'src/sagify/build.sh', u'src', u'src', u'src/sagify/Dockerfile', u'src/requirements.txt', u'latest']' returned non-zero exit status 1

I think the problem is with the requirements.txt. I am using the exact same file just adding 2 new packages sklearn and pandas in it.
Please need your help!

**Comment by pm3310** [comment]
Hey @royvasu, can you share your requirements.txt file please?

**Comment by royvasu** [comment]
@pm3310 I have shared the two files for the reference - 

[Dockerfile.txt](https://github.com/Kenza-AI/sagify/files/2632894/Dockerfile.txt)
[requirements.txt](https://github.com/Kenza-AI/sagify/files/2632896/requirements.txt)

**Comment by pm3310** [comment]
@royvasu Thanks for sharing the files. They look valid to me. 
Have you used this example https://github.com/Kenza-AI/deep-learning-addition to build on top?

If you run `src/sagify/build.sh src src src/sagify/Dockerfile src/requirements.txt latest`, you should get the exact error message.

Alternatively, there is a verbose option to get it `sagify -v build ...`

**Comment by pm3310** [comment]
@royvasu I managed to run `sagify build -d src -r requirements.txt` successfully with your given `requirements.txt` using the latest sagify version (0.14.1) and Python3.6

**Comment by pm3310** [comment]
Closing it as there is not answer
