### ISSUE TITLE
New projects only allow 'src' to be the root dir

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#81]
If I pass any name during init when setting up a new project, I always get 'src' as the sagify module dir.

Is this by design @pm3310 ?

**Comment by pm3310** [comment]
Are you sure @ilazakis ? I'll check it out

**Comment by pm3310** [comment]
Hey @ilazakis, I just realised what you meant. Yes, for completely new project (i.e. there isn't already any root code directory), sagify creates always a `src`. In case, you have already a repo with some root code directory in place (for example, `my_root`), then you can specify a different one:
```
Are you starting a new project? [y/N]: N
Type in the directory where your code lives. Example: src: my_root
```
In other words, if you respond `N` to question `Are you starting a new project?`, you can specify where the root dir is located

**Comment by ilazakis** [comment]
@pm3310 ‘src’ is a common directory for other things though. Also, why remove the ability to name the folder however you like for new projects?

**Comment by pm3310** [comment]
yeah, if you have already a `src` directory, you re `y` to question `Are you starting a new project?` and then tell to sagify to create the sagify module under `src`
