### ISSUE TITLE
Support for custom / user-defined endpoint names

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#90]
I’d like to be able to define a name for the endpoint when I call ‘deploy’ for easier later processing and testing.

[Docs](https://sagemaker.readthedocs.io/en/stable/model.html)

**Comment by ilazakis** [comment]
@pm3310 this is basically the same thing we did in #88

**Comment by pm3310** [comment]
Duplicate of https://github.com/Kenza-AI/sagify/issues/91
