### ISSUE TITLE
Add ability to define endpoint name

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#91]
I'd like to be able to define the [endpoint name](https://sagemaker.readthedocs.io/en/stable/model.html#sagemaker.model.Model.deploy) when deploying a model for later analysis / configuration changes etc.

We'd have to add the new param on the [deploy method](https://github.com/Kenza-AI/sagify/blob/5c24db5ad084dd1cd0e533f349c350ada4a3d0cc/sagify/sagemaker/sagemaker.py#L233) as usual.

**Comment by pm3310** [comment]
https://github.com/Kenza-AI/sagify/pull/93
