### ISSUE TITLE
Add ability to update endpoints

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#94]
**What**
Ability (new command or probably better an *update* option on the existing *deploy* command) to update an endpoint’s configuration. As of today, if we deploy an endpoint there’s no way of amending its configuration e.g. instance type.

Running `deploy` using different params and the same endpoint name does not work unfortunately, *SageMaker* throws a duplicate endpoint exception.

**Comment by pm3310** [comment]
Hey @ilazakis, I'm thinking to add the update endpoint functionality like this:
```
sagify cloud deploy -m s3://my-bucket/output/model.tar.gz -n 3 -e ml.m4.xlarge --endpoint-name my-endpoint --overwrite
```

Essentially, I'll add a new flag argument `--overwrite` that will require the --endpoint-name to be compulsory as we need to know which endpoint to update. What are your thoughts?

**Comment by ilazakis** [comment]
Looks good @pm3310 . The only alternative I can think of at the moment is implicitly updating if the endpoint name already exists. 

That is, if `endoint-name` is provided, check if an endpoint with that name exists; yes -> call SageMaker’s update config API(s), no -> create new endpoint. 

This has the advantage of no new options being added and less work (I think) needed both for the PR and end users.

**Comment by pm3310** [comment]
Gotcha! I'll follow your advice @ilazakis

**Comment by pm3310** [comment]
https://github.com/Kenza-AI/sagify/pull/95
