### ISSUE TITLE
Wrong Batch Transform exit code for failed jobs

### ISSUE THREAD

**Issue by ilazakis** [Kenza-AI/sagify#97]
When a batch transform job fails, _Sagify_ still returns a 0 exit code.

We need to check the _SageMaker_ status returned [here](https://github.com/Kenza-AI/sagify/blob/b3df7177974786f048afb6b16a8d9a641b9d1495/sagify/commands/cloud.py#L482) and exit with 1 or similar if the status is `Failed` (not sure if we can future proof this in case _SageMaker_ changes the literal from _Failed_ to something else but should be easy to catch).

**Comment by pm3310** [comment]
https://github.com/Kenza-AI/sagify/pull/98
